---
- name: "set git email"
  become_user: "{{ username }}"
  shell: "/usr/bin/git config --global user.email '{{ git_email }}'"
  args:
    executable: "/bin/zsh"

- name: "set git username"
  become_user: "{{ username }}"
  shell: "/usr/bin/git config --global user.name '{{ git_name }}'" 
  args:
    executable: "/bin/zsh"